In [23]:
import pandas as pd
import numpy as np


# Generate any random value

In [24]:
np.random.random()

0.7552491914592435

# Generate same random value



In [25]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [26]:
np.random.uniform(1, 100)

72.31212485077366

In [27]:
np.random.randint(1, 10, 12).reshape(3, 4)

array([[6, 1, 1, 2],
       [8, 7, 3, 5],
       [6, 3, 5, 3]])

In [28]:
a = np.random.randint(1,10,4)
a

array([5, 8, 8, 2])

In [29]:
np.argmin(a)

3

In [30]:
np.where(a%2==1, a-1, a)

array([4, 8, 8, 2])

In [31]:
np.percentile(a, 90)

8.0


# Plotly


In [32]:
import plotly.offline as pyo
import plotly.graph_objs as go

In [33]:
match = pd.read_csv('matches.csv')
delivery = pd.read_csv('deliveries.csv')
ipl = delivery.merge(match, left_on='match_id', right_on='id')

In [34]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150460 entries, 0 to 150459
Data columns (total 39 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   match_id          150460 non-null  int64  
 1   inning            150460 non-null  int64  
 2   batting_team      150460 non-null  object 
 3   bowling_team      150460 non-null  object 
 4   over              150460 non-null  int64  
 5   ball              150460 non-null  int64  
 6   batsman           150460 non-null  object 
 7   non_striker       150460 non-null  object 
 8   bowler            150460 non-null  object 
 9   is_super_over     150460 non-null  int64  
 10  wide_runs         150460 non-null  int64  
 11  bye_runs          150460 non-null  int64  
 12  legbye_runs       150460 non-null  int64  
 13  noball_runs       150460 non-null  int64  
 14  penalty_runs      150460 non-null  int64  
 15  batsman_runs      150460 non-null  int64  
 16  extra_runs        15

In [35]:
top50 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending= False).head(50).index.to_list()
new_ipl = ipl[ipl['batsman'].isin(top50)]

In [36]:
runs = new_ipl.groupby('batsman')['batsman_runs'].sum()
balls = new_ipl.groupby('batsman')['batsman_runs'].count()

sr = (runs/balls) * 100
sr = sr.reset_index()

In [37]:
out = ipl[ipl['player_dismissed'].isin(top50)]
nouts = out['player_dismissed'].value_counts()
avg = runs/nouts
avg = avg.reset_index()
avg.rename(columns= {'index': 'batsman', 0: 'avg'}, inplace=True)
avg = avg.merge(sr, on='batsman')

In [38]:
avg

batsman        avg  batsman_runs
0     AB de Villiers  38.307692    145.129059
1       AC Gilchrist  27.223684    133.054662
2           AJ Finch  27.186441    126.299213
3          AM Rahane  33.593407    117.486549
4          AT Rayudu  27.146067    123.014257
5        BB McCullum  28.112245    126.318203
6           BJ Hodge  33.333333    121.422376
7           CH Gayle  41.022472    144.194313
8          DA Miller  34.733333    137.709251
9          DA Warner  40.140000    138.318401
10          DJ Bravo  22.945455    122.286822
11         DJ Hussey  26.979592    120.072661
12  DPMD Jayawardene  28.250000    118.791064
13          DR Smith  28.392857    132.279534
14      F du Plessis  30.116279    124.161074
15         G Gambhir  31.541985    120.361200
16        GJ Maxwell  25.081633    157.564103
17         JH Kallis  28.552941    105.936272
18         JP Duminy  39.860000    121.970624
19        KA Pollard  28.707317    140.621266
20     KC Sangakkara  25.953846    118.469101
21        KD Karthik  24.811966    123.008475
22           KK Nair  25.173913    124.650161
23           M Vijay  26.431579    120.028681
24        MEK Hussey  38.764706    119.963592
25         MK Pandey  28.500000    116.938453
26         MK Tiwary  29.428571    114.127424
27          MS Dhoni  37.872340    132.835821
28           NV Ojha  20.986486    114.528024
29          PA Patel  21.700935    112.718447
30          R Dravid  28.233766    113.347237
31         RA Jadeja  24.055556    118.792867
32         RG Sharma  32.612403    128.497251
33        RV Uthappa  29.515625    127.635135
34       S Badrinath  30.659574    115.742972
35          S Dhawan  32.669725    118.502496
36        SC Ganguly  25.452830    101.734540
37          SE Marsh  39.507937    130.109775
38          SK Raina  33.940299    134.995548
39         SPD Smith  37.239130    128.507127
40      SR Tendulkar  33.826087    114.187867
41         SR Watson  30.917647    134.838379
42         SS Tiwary  28.355556    114.851485
43         SV Samson  25.464286    122.403433
44        TM Dilshan  26.813953    110.124164
45           V Kohli  37.483051    126.588437
46          V Sehwag  27.555556    148.827059
47           WP Saha  25.524590    127.727646
48         YK Pathan  29.816327    140.751445
49      Yuvraj Singh  25.653465    126.390244

# Scatter

In [63]:
trace=go.Scatter(x=avg['avg'], y=avg['batsman_runs'], mode='markers', text=avg['batsman'], marker={'color':'#00a65a', 'size':14})
data=[trace]
layout=go.Layout(title='Batsman avg vs SR',
                xaxis={'title':'Average'},
                yaxis={'title':'Strike rate'})
fig=go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

# Line

In [40]:
single=ipl[ipl['batsman']=='V Kohli']
perfomance=single.groupby('season')['batsman_runs'].sum().reset_index()
perfomance

season  batsman_runs
0    2008           165
1    2009           246
2    2010           307
3    2011           557
4    2012           364
5    2013           639
6    2014           359
7    2015           505
8    2016           973
9    2017           308

In [41]:
single1=ipl[ipl['batsman']=='AB de Villiers']
perfomance1=single1.groupby('season')['batsman_runs'].sum().reset_index()
perfomance1

season  batsman_runs
0    2008            95
1    2009           465
2    2010           111
3    2011           312
4    2012           319
5    2013           373
6    2014           395
7    2015           513
8    2016           687
9    2017           216

In [42]:
trace = go.Scatter(x=perfomance['season'], y=perfomance['batsman_runs'],
                  mode='lines+markers', marker={'color':'#00a65a', 'size':14}, name='V k')

trace1 = go.Scatter(x=perfomance1['season'], y=perfomance1['batsman_runs'],
                  mode='lines+markers', name='ABD')
data = [trace, trace1]
layout=go.Layout(title='Batsman perfomace',
                xaxis={'title':'season'},
                yaxis={'title':'perfomance'})
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

# Bar

In [43]:
top10 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending= False).head(10).index.to_list()
score = ipl[ipl['batsman'].isin(top10)]
score_df = score.groupby('batsman')['batsman_runs'].sum().reset_index()

In [44]:
trace = go.Bar(x=score_df['batsman'], y=score_df['batsman_runs'])

data = [trace]
layout=go.Layout(title='Top 10',
                xaxis={'title':'Batsman'},
                yaxis={'title':'Runs'})
fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [55]:
new_ipl = new_ipl[new_ipl['batsman_runs'] == 6]
six = new_ipl.groupby('batsman')['batsman_runs'].count().reset_index()
x=avg.merge(six, on='batsman')

# Bubble plot

In [67]:
trace=go.Scatter(x=x['avg'], y=x['batsman_runs_x'], mode='markers',
                marker={'size':x['batsman_runs_y']}, text=x['batsman'])
data=[trace]
layout=go.Layout(title='Bubble Chart',
                xaxis={'title':'Average'},
                yaxis={'title':'Strike rate'})
fig=go.Figure(data=data,layout=layout)

pyo.plot(fig)


'temp-plot.html'

# Box plot

In [73]:
match_agg = ipl.groupby('match_id')['total_runs'].sum().reset_index()
season_wise=match_agg.merge(match, left_on='match_id', right_on='id')[['match_id', 'total_runs', 'season']]
season_wise

match_id  total_runs  season
0           1         379    2017
1           2         371    2017
2           3         367    2017
3           4         327    2017
4           5         299    2017
..        ...         ...     ...
631       632         277    2016
632       633         317    2016
633       634         302    2016
634       635         325    2016
635       636         408    2016

[636 rows x 3 columns]

In [75]:
season_17=season_wise[season_wise['season'] == 2017]
season_16=season_wise[season_wise['season'] == 2016]
trace=go.Box(x=season_17['total_runs'],name="2017")
trace1=go.Box(x=season_16['total_runs'],name="2016")

data=[trace, trace1]
layout=go.Layout(title='Total score analysis',
                xaxis={'title':'Total score'
                })

fig=go.Figure(data=data, layout=layout)

pyo.plot(fig)

'temp-plot.html'

# heatmap

In [85]:
dots=delivery[delivery['batsman_runs']==0]
dots=dots.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
six = delivery[delivery['batsman_runs'] == 6]
six = six.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
six

batting_team  over  batsman_runs
0    Chennai Super Kings     1             5
1    Chennai Super Kings     2            17
2    Chennai Super Kings     3            37
3    Chennai Super Kings     4            34
4    Chennai Super Kings     5            41
..                   ...   ...           ...
271  Sunrisers Hyderabad    16            22
272  Sunrisers Hyderabad    17            18
273  Sunrisers Hyderabad    18            37
274  Sunrisers Hyderabad    19            42
275  Sunrisers Hyderabad    20            28

[276 rows x 3 columns]

In [87]:
from plotly import tools

trace1=go.Heatmap(x=six['batting_team'], y =six['over'], z=six['batsman_runs'].values.tolist())
trace2=go.Heatmap(x=dots['batting_team'], y =dots['over'], z=dots['batsman_runs'].values.tolist())
fig = tools.make_subplots(rows=1, cols=2, subplot_titles=["6", "0"], shared_yaxes=True)

fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)

pyo.plot(fig)

'temp-plot.html'